kind: Service
apiVersion: v1
metadata:
  name: httpservice
  labels:
    app: httpservice
spec:
  ports:
  - port: 80
    targetPort: http
---
kind: Pod
apiVersion: v1
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: webhello
    image: strm/helloworld-http
    ports:
    - name: http
      containerPort: 80
